global:
  scrape_interval: 60s

scrape_configs:
  - job_name: "unifi-exporter"
    static_configs:
      - targets: ["unifi-exporter:9100"]

  - job_name: "unifi-gateway"
    static_configs:
      - targets: ["unifi-gateway:8080"]
